namespace ShinRoll.Models.Enums
{
    public enum OriginEnum
    {
        None = 0,
        PandemicSurvivor = 1,
        Experiment =2,
        SonOfTheDevil = 3 ,
        ExAgentCipherPol = 4,
        Thief = 5,
        BornInWar = 6,
        Mobster = 7,
        Gladiator = 8,
        FamilyMan = 9,
        Worker = 10,
        Oppressed = 11,
        DevoteeOfDavyJones = 12,
        Guardian = 13,
        Glutton = 14,
        MadScientist = 15,
        Tormented = 16,
        Admirer = 17,
        HeredeInDisenchantment = 18,
        BornToKill = 19,
        Martyr = 20,
        CapitalSpecialist= 21,
        CommunityHero = 22,
        Circus = 22,
        DiscipleOfBushido = 23,
        ApprenticeOfLegend = 24,
        Opportunist =25,
        Usurped = 26,
        Explorer = 27,
        ExperientHealer = 28,
        Witch = 29,
        Psychologist = 30,
        Farce = 31,
        FreeSpirit = 32,
        ToxicFamily = 33,
        AspiringHero = 34,
        GodComplex = 35,
        MemoryVoid = 36,
        Homeless = 37,
        SearchingForRedemption = 38,
        HeraldOfTheNewEra = 39,
        LadyNight = 40,
        Survivor = 41,
        InnateTrust = 42,
        KidOfTheSea = 43,
        Errant = 44,
        RenegadeLeader = 45,
        UnstoppableDreamer = 46,
        Protegee = 47,
        LastingRivalry = 48,
        Infiltrated = 49,
        ConsciousAndroid = 50,
        Problematic = 51,
        SonOfHeavenAndHell = 52,



    }
}
