// <auto-generated />
using System.Collections.Generic;
using Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ShinRoll.Migrations
{
    [DbContext(typeof(AppDbContextPOSTGRES))]
    [Migration("20260221093639_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShinRoll.Data.StaticData.CharacterSpecs.FightingStyles.FightingStyleStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<int[]>("CDAttributes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("FavoriteWeapon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FightingStyle")
                        .HasColumnType("integer");

                    b.Property<int>("LifeDice")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("PrimaryAttribute")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("SavingBonus")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("SkillToChoose")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("SkillsProficiency")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("WeaponProficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FightingStyleStats");
                });

            modelBuilder.Entity("ShinRoll.Data.StaticData.CharacterSpecs.Origin.OriginStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Origin")
                        .HasColumnType("integer");

                    b.Property<string>("OriginName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("RecommendedAttribute")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("SkillToChoose")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("SkillsProficiency")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("SpecialAbilityDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecialAbilityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OriginStats");
                });

            modelBuilder.Entity("ShinRoll.Data.StaticData.CharacterSpecs.Profession.ProfessionStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("Details")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Profession")
                        .HasColumnType("integer");

                    b.Property<int>("SkillToChoose")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("SkillsProficiency")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("SpecialSkill")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecialSkillName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProfessionStats");
                });

            modelBuilder.Entity("ShinRoll.Data.StaticData.CharacterSpecs.Species.SpeciesStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseLifePoints")
                        .HasColumnType("integer");

                    b.Property<string>("Beneficts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Harms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Moviment")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Species")
                        .HasColumnType("integer");

                    b.Property<string>("SubSpecieName")
                        .HasColumnType("text");

                    b.Property<int?>("SubSpecies")
                        .HasColumnType("integer");

                    b.Property<double>("Swimming")
                        .HasColumnType("double precision");

                    b.Property<string>("VariantDescription")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SpeciesStats");
                });

            modelBuilder.Entity("ShinRoll.Data.StaticData.CharacterSpecs.Technique.TechniqueStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionRequirement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CanCombineAttack")
                        .HasColumnType("boolean");

                    b.Property<long?>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Degree")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PowerPointCost")
                        .HasColumnType("integer");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("TechniqueStats");
                });

            modelBuilder.Entity("ShinRoll.Data.StaticData.Skill.SkillsData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Acrobatics")
                        .HasColumnType("integer");

                    b.Property<int>("Athletics")
                        .HasColumnType("integer");

                    b.Property<int>("Deception")
                        .HasColumnType("integer");

                    b.Property<int?>("FightingStyleStatsId")
                        .HasColumnType("integer");

                    b.Property<int>("Haki")
                        .HasColumnType("integer");

                    b.Property<int>("History")
                        .HasColumnType("integer");

                    b.Property<int>("Insight")
                        .HasColumnType("integer");

                    b.Property<int>("Intimidation")
                        .HasColumnType("integer");

                    b.Property<int>("Investigation")
                        .HasColumnType("integer");

                    b.Property<int>("Luck")
                        .HasColumnType("integer");

                    b.Property<int>("Nature")
                        .HasColumnType("integer");

                    b.Property<int>("Perception")
                        .HasColumnType("integer");

                    b.Property<int>("Performance")
                        .HasColumnType("integer");

                    b.Property<int>("Persuasion")
                        .HasColumnType("integer");

                    b.Property<int>("Profession")
                        .HasColumnType("integer");

                    b.Property<int>("Provoke")
                        .HasColumnType("integer");

                    b.Property<int>("SleightOfHand")
                        .HasColumnType("integer");

                    b.Property<int>("Stealth")
                        .HasColumnType("integer");

                    b.Property<int>("Supernatural")
                        .HasColumnType("integer");

                    b.Property<int>("Survival")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FightingStyleStatsId");

                    b.ToTable("SkillsData");
                });

            modelBuilder.Entity("ShinRoll.Models.Attributes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Constitution")
                        .HasColumnType("integer");

                    b.Property<int>("Dexterity")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<int>("ModConstituition")
                        .HasColumnType("integer");

                    b.Property<int>("ModDexterity")
                        .HasColumnType("integer");

                    b.Property<int>("ModPresence")
                        .HasColumnType("integer");

                    b.Property<int>("ModStrenght")
                        .HasColumnType("integer");

                    b.Property<int>("ModWill")
                        .HasColumnType("integer");

                    b.Property<int>("ModWisdom")
                        .HasColumnType("integer");

                    b.Property<int>("Presence")
                        .HasColumnType("integer");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<int>("Will")
                        .HasColumnType("integer");

                    b.Property<int>("Wisdom")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Attributes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Attributes");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ShinRoll.Models.Character", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<int[]>("AllowedSkills")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<long>("AttributesId")
                        .HasColumnType("bigint");

                    b.Property<int>("DifficultyClass")
                        .HasColumnType("integer");

                    b.Property<int>("FightingStyleId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OriginId")
                        .HasColumnType("integer");

                    b.Property<int>("PointsOfEnergy")
                        .HasColumnType("integer");

                    b.Property<int>("PointsOfLife")
                        .HasColumnType("integer");

                    b.Property<int>("ProfessionId")
                        .HasColumnType("integer");

                    b.Property<int>("Proficiency")
                        .HasColumnType("integer");

                    b.Property<long>("SavingBonusId")
                        .HasColumnType("bigint");

                    b.Property<int>("SkillsId")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubSpecie")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttributesId");

                    b.HasIndex("FightingStyleId");

                    b.HasIndex("OriginId");

                    b.HasIndex("ProfessionId");

                    b.HasIndex("SavingBonusId");

                    b.HasIndex("SkillsId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("characters");
                });

            modelBuilder.Entity("ShinRoll.Data.StaticData.CharacterSpecs.SavingBonus.SavingBonusStats", b =>
                {
                    b.HasBaseType("ShinRoll.Models.Attributes");

                    b.HasDiscriminator().HasValue("SavingBonusStats");
                });

            modelBuilder.Entity("ShinRoll.Data.StaticData.CharacterSpecs.Technique.TechniqueStats", b =>
                {
                    b.HasOne("ShinRoll.Models.Character", null)
                        .WithMany("Techniques")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("ShinRoll.Data.StaticData.Skill.SkillsData", b =>
                {
                    b.HasOne("ShinRoll.Data.StaticData.CharacterSpecs.FightingStyles.FightingStyleStats", null)
                        .WithMany("SkillsAllowed")
                        .HasForeignKey("FightingStyleStatsId");
                });

            modelBuilder.Entity("ShinRoll.Models.Character", b =>
                {
                    b.HasOne("ShinRoll.Models.Attributes", "Attributes")
                        .WithMany()
                        .HasForeignKey("AttributesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShinRoll.Data.StaticData.CharacterSpecs.FightingStyles.FightingStyleStats", "FightingStyle")
                        .WithMany()
                        .HasForeignKey("FightingStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShinRoll.Data.StaticData.CharacterSpecs.Origin.OriginStats", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShinRoll.Data.StaticData.CharacterSpecs.Profession.ProfessionStats", "Profession")
                        .WithMany()
                        .HasForeignKey("ProfessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShinRoll.Data.StaticData.CharacterSpecs.SavingBonus.SavingBonusStats", "SavingBonus")
                        .WithMany()
                        .HasForeignKey("SavingBonusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShinRoll.Data.StaticData.Skill.SkillsData", "Skills")
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShinRoll.Data.StaticData.CharacterSpecs.Species.SpeciesStats", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attributes");

                    b.Navigation("FightingStyle");

                    b.Navigation("Origin");

                    b.Navigation("Profession");

                    b.Navigation("SavingBonus");

                    b.Navigation("Skills");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ShinRoll.Data.StaticData.CharacterSpecs.FightingStyles.FightingStyleStats", b =>
                {
                    b.Navigation("SkillsAllowed");
                });

            modelBuilder.Entity("ShinRoll.Models.Character", b =>
                {
                    b.Navigation("Techniques");
                });
#pragma warning restore 612, 618
        }
    }
}
