// <auto-generated />
using Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ShinRoll.Migrations
{
    [DbContext(typeof(AppDbContextPOSTGRES))]
    [Migration("20260223000718_atualizarDB")]
    partial class atualizarDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShinRoll.Data.StaticData.CharacterSpecs.FightingStyles.FightingStyleStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<int[]>("CDAttributes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("FavoriteWeapon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FightingStyle")
                        .HasColumnType("integer");

                    b.Property<int>("LifeDice")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("PrimaryAttribute")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("SavingBonus")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("SkillToChoose")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("SkillsProficiency")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("WeaponProficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FightingStyleStats");
                });

            modelBuilder.Entity("ShinRoll.Models.Attributes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Constitution")
                        .HasColumnType("integer");

                    b.Property<int>("Dexterity")
                        .HasColumnType("integer");

                    b.Property<int>("ModConstituition")
                        .HasColumnType("integer");

                    b.Property<int>("ModDexterity")
                        .HasColumnType("integer");

                    b.Property<int>("ModPresence")
                        .HasColumnType("integer");

                    b.Property<int>("ModStrenght")
                        .HasColumnType("integer");

                    b.Property<int>("ModWill")
                        .HasColumnType("integer");

                    b.Property<int>("ModWisdom")
                        .HasColumnType("integer");

                    b.Property<int>("Presence")
                        .HasColumnType("integer");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<int>("Will")
                        .HasColumnType("integer");

                    b.Property<int>("Wisdom")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("ShinRoll.Models.Character", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<int[]>("AllowedSkills")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<long>("AttributesId")
                        .HasColumnType("bigint");

                    b.Property<int>("DifficultyClass")
                        .HasColumnType("integer");

                    b.Property<int>("FightingStyleId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PointsOfEnergy")
                        .HasColumnType("integer");

                    b.Property<int>("PointsOfLife")
                        .HasColumnType("integer");

                    b.Property<int>("Proficiency")
                        .HasColumnType("integer");

                    b.Property<int?>("SubSpecie")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttributesId");

                    b.HasIndex("FightingStyleId");

                    b.ToTable("characters");
                });

            modelBuilder.Entity("ShinRoll.Models.Character", b =>
                {
                    b.HasOne("ShinRoll.Models.Attributes", "Attributes")
                        .WithMany()
                        .HasForeignKey("AttributesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShinRoll.Data.StaticData.CharacterSpecs.FightingStyles.FightingStyleStats", "FightingStyle")
                        .WithMany()
                        .HasForeignKey("FightingStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attributes");

                    b.Navigation("FightingStyle");
                });
#pragma warning restore 612, 618
        }
    }
}
